// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CoChanges(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CoChanges'](arg1, arg2, arg3, arg4, arg5);
}

export function CommitHeatmap(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitHeatmap'](arg1, arg2, arg3);
}

export function CommitsByHour(arg1, arg2) {
  return window['go']['main']['App']['CommitsByHour'](arg1, arg2);
}

export function Contributors(arg1, arg2, arg3) {
  return window['go']['main']['App']['Contributors'](arg1, arg2, arg3);
}

export function DashboardStats(arg1, arg2) {
  return window['go']['main']['App']['DashboardStats'](arg1, arg2);
}

export function FileHotspots(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileHotspots'](arg1, arg2, arg3);
}

export function FileOwnerships(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileOwnerships'](arg1, arg2, arg3);
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function RecentRepos() {
  return window['go']['main']['App']['RecentRepos']();
}

export function RemoveRecentRepo(arg1) {
  return window['go']['main']['App']['RemoveRecentRepo'](arg1);
}

export function RepoInfo() {
  return window['go']['main']['App']['RepoInfo']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function TemporalHotspots(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TemporalHotspots'](arg1, arg2, arg3, arg4);
}
