// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {query} from '../models';

export function CommitHeatmap(arg1:string,arg2:string,arg3:string):Promise<Array<query.HeatmapDay>>;

export function Contributors(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<query.Contributor>>;

export function FileHotspots(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<query.FileHotspot>>;

export function FileOwnerships(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<query.FileOwnership>>;

export function OpenRepository(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function TemporalHotspots(arg1:string,arg2:string,arg3:number,arg4:Array<string>):Promise<Array<query.TemporalHotspot>>;
