// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CommitHeatmap(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitHeatmap'](arg1, arg2, arg3);
}

export function Contributors(arg1, arg2, arg3) {
  return window['go']['main']['App']['Contributors'](arg1, arg2, arg3);
}

export function FileHotspots(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileHotspots'](arg1, arg2, arg3);
}

export function FileOwnerships(arg1, arg2, arg3) {
  return window['go']['main']['App']['FileOwnerships'](arg1, arg2, arg3);
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
